# updated dvc.yaml

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
    - data/interim

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/interim
    - src/data/data_preprocessing.py
    outs:
    - data/processed


  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - src/models/model_building.py
    outs:
    - model/model.pkl

  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - model/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  

  model_registration:
    cmd: python src/models/register_model.py
    deps:
    - reports/experiment_info.json
    - src/models/register_model.py